PocketSphinx install (#27)
Added test for linux-gnu OS type
Added test for 'apt' utility  (exit 1 if not found)
Added test + installers for:
- swig
- libpulse-dev
- libasound2-dev

Co-authored-by: Adarsh Pyarelal <adarsh@arizona.edu>

diff --git a/agents/asr/install_pocketsphinx_python b/agents/asr/install_pocketsphinx_python
--- a/agents/asr/install_pocketsphinx_python
+++ b/agents/asr/install_pocketsphinx_python
@@ -1,7 +1,6 @@
 #!/usr/bin/env bash
 
 # Script to install pocketsphinx-python
-# Author: Adarsh Pyarelal (adarsh@arizona.edu)
 
 set -euo pipefail
 
@@ -48,7 +47,6 @@ else
                     exit 1
                 fi
             fi
-
         fi
 
 
@@ -66,10 +64,55 @@ else
         echo "pocketsphinx-python installation successful."
         echo "Removing pocketsphinx-python directory."
         rm -rf pocketsphinx-python
+
+    elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
+        echo "Linux detected. Checking existence of the apt package manager."
+
+        CHECK_APT=$([ -x "$(command -v apt)" ]; echo $?)
+        if [[ $CHECK_APT -eq 0 ]]; then
+            echo "apt found"
+            CHECK_SWIG=$([ -x "$(command -v swig)" ]; echo $?)
+            if [[ $CHECK_SWIG -eq 0 ]]; then
+                echo "SWIG found"
+            else
+                echo "SWIG not found, installing it now."
+                sudo apt-get install swig
+            fi
+
+            INSTALLED_LIBS=$(ldconfig -p)
+
+            echo "Checking existence of libpulse"
+            if [[ "$INSTALLED_LIBS" == *"libpulse"* ]]; then
+                echo "libpulse found"
+            else
+                echo "Installing libpulse."
+                    sudo apt-get install libpulse-dev
+            fi
+
+            echo "Checking existence of libasound2"
+            if [[ "$INSTALLED_LIBS" == *"libasound.so.2"* ]]; then
+                echo "Found libasound2"
+            else 
+                echo "Installing libasound2"
+                sudo apt-get install libasound2-dev
+            fi
+        else
+            echo "Application 'apt' not found - this script"\
+                "cannot automatically install pocketsphinx-python."\
+                "Please install SWIG and the headers and libraries"\
+                "for PulseAudio and ALSA using your operating system's"\
+                "package manager, followed by running"\
+                "'pip install pocketsphinx'"
+            exit 1
+        fi
+
+        echo "Installing pocketsphinx-python using pip."
+            pip install pocketsphinx
+
     else
-        # This should theoretically work on Linux/Windows, but I have not tried it
-        # out. This comment should be removed if the command below succeeds on
-        # Linux/Windows. - Adarsh
+        # This should theoretically work on Windows, but it has not been
+        # tested. This comment should be removed if the command below succeeds
+        # on Windows.
         pip install pocketsphinx
     fi
 fi
