Added installation of libasound2-dev and libpulse-dev if needed

diff --git a/agents/asr/install_pocketsphinx_python b/agents/asr/install_pocketsphinx_python
--- a/agents/asr/install_pocketsphinx_python
+++ b/agents/asr/install_pocketsphinx_python
@@ -48,7 +48,6 @@ else
                     exit 1
                 fi
             fi
-
         fi
 
 
@@ -68,17 +67,36 @@ else
         rm -rf pocketsphinx-python
 
     elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
-        echo "Linux detected.  Checking existence of SWIG"
-        CHECK_SWIG=$([ -x "$(command -v swig)" ]; echo $?)
-        if [[ $CHECK_SWIG -eq 0 ]]; then
-            echo "SWIG found"
-        else
-            echo "SWIG not found, installing it now."
-            sudo apt-get install swig
-        fi
-	sudo apt-get install libpulse-dev   # test for existing install first?
-	sudo apt-get install libasound2-dev # test for existing install first?
+        echo "Linux detected.  Checking existence of apt"
+        CHECK_APT=$([ -x "$(command -v apt)" ]; echo $?)
+        if [[ $CHECK_APT -eq 0 ]]; then
+            echo "apt found"
+            CHECK_SWIG=$([ -x "$(command -v swig)" ]; echo $?)
+            if [[ $CHECK_SWIG -eq 0 ]]; then
+                echo "SWIG found"
+            else
+                echo "SWIG not found, installing it now."
+                sudo apt-get install swig
+            fi
 
+	    INSTALLED_LIBS=$(ldconfig -p)
+	    echo "Checking existence of libpulse"
+	    if [[ "$INSTALLED_LIBS" == *"libpulse"* ]]; then
+	        echo "libpulse found"
+            else 
+	        echo "Installing libpulse."
+                sudo apt-get install libpulse-dev
+	    fi
+	    echo "Checking existence of libasound2"
+	    if [[ "$INSTALLED_LIBS" == *"libasound.so.2"* ]]; then
+	        echo "Found libasound2"
+            else 
+	        echo "Installing libasound2"
+               sudo apt-get install libasound2-dev
+	    fi
+	fi    
+
+	echo "installing pocketsphinx"
         pip install pocketsphinx 
 
     else
