Adding Linux support, changing pip to pip3

diff --git a/scripts/download_opensmile b/scripts/download_opensmile
--- a/scripts/download_opensmile
+++ b/scripts/download_opensmile
@@ -9,12 +9,16 @@ set -u
 ROOTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../" >/dev/null 2>&1 && pwd)"
 export ROOTDIR
 
-if [[ ! $OSTYPE == "darwin"* ]]; then
-    echo "This script only works on macOS. Exiting now..."
-    exit 1
+if [[ $OSTYPE == "darwin"* ]]; then
+    DETECTED_OS=osx
+elif [[ $OSTYPE == "linux-gnu" ]]; then
+    DETECTED_OS=linux
+else 
+    echo "This is not macOS or linux, cannot execute script, exiting"
+    exit 1 
 fi
 
-TAR_GZ_FILE=opensmile-3.0-osx-x64.tar.gz
+TAR_GZ_FILE=opensmile-3.0-$DETECTED_OS-x64.tar.gz
 URL="https://github.com/audeering/opensmile/releases/download/v3.0.0/${TAR_GZ_FILE}"
 mkdir -p "$ROOTDIR"/external
 
@@ -29,7 +33,7 @@ pushd "$ROOTDIR"/external > /dev/null
     if ! tar -xzf "$TAR_GZ_FILE"; then
         echo "Error encountered while extracting ${TAR_GZ_FILE}. This seems to
         not affect the working of the OpenSMILE SMILEExtract binary."
-        mv opensmile-3.0-osx-x64 opensmile-3.0
+        mv opensmile-3.0-$DETECTED_OS-x64 opensmile-3.0
     fi
 popd > /dev/null
 
