Updated OpenSMILE download script to get v3.0.0, fixed path to binary in scripts

diff --git a/scripts/download_opensmile b/scripts/download_opensmile
--- a/scripts/download_opensmile
+++ b/scripts/download_opensmile
@@ -1,29 +1,35 @@
 #!/usr/bin/env bash
 
-set -euo pipefail
+set -u
 
-# Script to download OpenSmile v2.3.0
+# Script to download OpenSmile v3.0.0
 
 # Set the ROOTDIR environment variable, assuming that the directory structure
 # mirrors that of the git repository.
 ROOTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../" >/dev/null 2>&1 && pwd)"
 export ROOTDIR
 
-ZIPFILE=opensmile-2.3.0.zip
-URL="https://www.audeering.com/download/opensmile-2-3-0-zip/?wpdmdl=4781&refresh=5f06534ad91f31594250058"
+if [[ ! $OSTYPE == "darwin"* ]]; then
+    echo "This script only works on macOS. Exiting now..."
+    exit 1
+fi
+
+TAR_GZ_FILE=opensmile-3.0-osx-x64.tar.gz
+URL="https://github.com/audeering/opensmile/releases/download/v3.0.0/${TAR_GZ_FILE}"
 mkdir -p "$ROOTDIR"/external
 
 pushd "$ROOTDIR"/external > /dev/null
-    echo "Downloading OpenSmile to $(pwd)/${ZIPFILE}"
-    if ! curl "$URL" -o "$ZIPFILE"; then
+    echo "Downloading OpenSmile to $(pwd)/opensmile-3.0"
+    if ! curl -LO "$URL"; then
         echo "Could not download OpenSmile."
         exit 1
     fi
 
     echo "Extracting OpenSmile..."
-    if ! unzip "$ZIPFILE"; then
-        echo "Could not unzip ${ZIPFILE}"
-        exit 1
+    if ! tar -xzf "$TAR_GZ_FILE"; then
+        echo "Error encountered while extracting ${TAR_GZ_FILE}. This seems to
+        not affect the working of the OpenSMILE SMILEExtract binary."
+        mv opensmile-3.0-osx-x64 opensmile-3.0
     fi
 popd > /dev/null
 
